In [18]:
import os
import pandas as pd

os.makedirs("../outputs", exist_ok=True)

dados_df = pd.read_csv("../data/meios_pagamentos_2023_2025.csv")

print(dados_df.columns)
dados_df.head()

Index(['AnoMes', 'quantidadePix', 'valorPix', 'quantidadeTED',
       'quantidadeBoleto', 'valorBoleto'],
      dtype='object')

,AnoMes,quantidadePix,valorPix,quantidadeTED,quantidadeBoleto,valorBoleto
0,202507,6698196.91,3497412.52,67192.89,353819.55,564569.38
1,202506,6464330.71,2869832.97,62477.43,338127.37,523439.24
2,202505,6643181.01,2822151.77,64178.98,340006.42,532979.61
3,202504,6278102.30,2676807.81,64449.00,341624.79,539022.34
4,202503,6249384.72,2570468.46,61294.83,340788.00,516117.79

#### Verificando se há valores nulos

In [21]:
print(" Valores nulos por coluna:")
print(dados_df.isnull().sum())

🔎 Valores nulos por coluna:
ano_mes         0
qtd_pix         0
valor_pix       0
qtd_ted         0
qtd_boleto      0
valor_boleto    0
dtype: int64

#### Renomeando colunas para padrão snake_case

In [19]:
dados_df = dados_df.rename(columns={
    "AnoMes": "ano_mes",
    "quantidadePix": "qtd_pix",
    "valorPix": "valor_pix",
    "quantidadeTED": "qtd_ted",
    "valorTED": "valor_ted",
    "quantidadeTEC": "qtd_tec",
    "valorTEC": "valor_tec",
    "quantidadeCheque": "qtd_cheque",
    "valorCheque": "valor_cheque",
    "quantidadeBoleto": "qtd_boleto",
    "valorBoleto": "valor_boleto",
    "quantidadeDOC": "qtd_doc",
    "valorDOC": "valor_doc"
})

dados_df.head()

   ano_mes     qtd_pix   valor_pix   qtd_ted  qtd_boleto  valor_boleto
0   202507  6698196.91  3497412.52  67192.89   353819.55     564569.38
1   202506  6464330.71  2869832.97  62477.43   338127.37     523439.24
2   202505  6643181.01  2822151.77  64178.98   340006.42     532979.61
3   202504  6278102.30  2676807.81  64449.00   341624.79     539022.34
4   202503  6249384.72  2570468.46  61294.83   340788.00     516117.79

#### Garantindo colunas numéricas e strings

In [23]:

dados_df["ano_mes"] = dados_df["ano_mes"].astype(str)

colunas_numericas = [
    "qtd_pix", "valor_pix",
    "qtd_ted", "valor_ted",
    "qtd_tec", "valor_tec",
    "qtd_cheque", "valor_cheque",
    "qtd_boleto", "valor_boleto",
    "qtd_doc", "valor_doc"
]

for col in colunas_numericas:
    if col in dados_df.columns:
        dados_df[col] = pd.to_numeric(dados_df[col], errors="coerce")

print(dados_df.dtypes)
dados_df.head()

ano_mes          object
qtd_pix         float64
valor_pix       float64
qtd_ted         float64
qtd_boleto      float64
valor_boleto    float64
dtype: object

  ano_mes     qtd_pix   valor_pix   qtd_ted  qtd_boleto  valor_boleto
0  202507  6698196.91  3497412.52  67192.89   353819.55     564569.38
1  202506  6464330.71  2869832.97  62477.43   338127.37     523439.24
2  202505  6643181.01  2822151.77  64178.98   340006.42     532979.61
3  202504  6278102.30  2676807.81  64449.00   341624.79     539022.34
4  202503  6249384.72  2570468.46  61294.83   340788.00     516117.79

#### Salvando dados tratados

In [22]:
dados_df.to_csv("../outputs/meios_pagamentos_tratados.csv", index=False, encoding="utf-8-sig")

dados_df.to_json("../outputs/meios_pagamentos_tratados.json", orient="records", force_ascii=False, indent=4)

print("✅ Arquivos consolidados e tratados salvos em ../outputs/")

✅ Arquivos consolidados e tratados salvos em ../outputs/